before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: d86XEUmfBSguC0guF9ydhvHyhzS3EwhQKbfAW80WQBYYoywCP5QlYphdh+qiUjMf1ZjdnANpKiBb14dEDNVK+oEt/bqNoobRrdYyitR/0OPGV4+Rsi1FQuTMx+t63gc1KIhyhLZknudab/m5O1Ts6p3D4wr2k9VgUfhVfbtsxPqFTWgF35zhXVUvuQ4mfbTalho0f9APWGpG7442ACp0BxKF9xibO4PYK9wpkOcosuaisllWOm8fN+R3Nb9hcQuJSwVpQ0ftM+UQvSHVEbk1tuknTxFJBk8zIJans0AKWV5d5IVeM2rPuFl5yBYbakitvlS3ffDJUncZqowsIYGfMV8gKNcy6isz5Ym8ALr6lsT/CEJk0WIBKQIPKDBqBkP6Z0CKrdwG8OUSHpOIygjB32sRBLwbw8MNBF0pXFnAatiqh3l9InmxYsgN650oue+ASn8dmBtpk8wOtREdfbu33f0g4SerXq4upm3cir0G6HW8gl3qmdGc++4SAk/RUMNRyvPIYafZN2sVMup7a2coKpwfh9wf1zSb5IH9iFWnXDtO901rCvC63NclBkVALHkoDj3DFTzP/ve7lj0D7rsZ1RFCS1F0RLhVz7fYuCbGAcN84tNHHTFV/j0KTXLpqdvn3QmFqsHWiCFtSbeWCIDoCoKZ5WxzelwFtS+ydqnYjKQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
